name: Playwright test demoQA
on: 
  push:
    branches:
      - 'main'

jobs:
    test:
      runs-on: ubuntu-latest

      steps:
        - uses: actions/checkout@v2

        - name: Use Node.js
          uses: actions/setup-node@v2
          with:
            node-version: '16'
        
        - name: Cache playwright dependencies
          uses: actions/cache@v2
          with:
            path: node_modules
            key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
            restore-keys: |
              ${{ runner.os }}-node-

        - name: Install dependencies
          run: npm install

        - name: Install playwright browsers
          run: npx playwright install

        - name: Run tests
          run: npm run test:all